//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaWolf {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeawolfResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeawolfResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SeaWolf.SeawolfResources", typeof(SeawolfResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Common_Exit {
            get {
                return ResourceManager.GetString("Common_Exit", resourceCulture);
            }
        }
        
        internal static string Common_GetStarted {
            get {
                return ResourceManager.GetString("Common_GetStarted", resourceCulture);
            }
        }
        
        internal static string Common_SelectCommand {
            get {
                return ResourceManager.GetString("Common_SelectCommand", resourceCulture);
            }
        }
        
        internal static string ComponentView_Configuration {
            get {
                return ResourceManager.GetString("ComponentView_Configuration", resourceCulture);
            }
        }
        
        internal static string MainView_NoRegisteredDevices {
            get {
                return ResourceManager.GetString("MainView_NoRegisteredDevices", resourceCulture);
            }
        }
        
        internal static string PairDevice_Title {
            get {
                return ResourceManager.GetString("PairDevice_Title", resourceCulture);
            }
        }
        
        internal static string Provision_BT_Address {
            get {
                return ResourceManager.GetString("Provision_BT_Address", resourceCulture);
            }
        }
        
        internal static string Provision_CellEnabled {
            get {
                return ResourceManager.GetString("Provision_CellEnabled", resourceCulture);
            }
        }
        
        internal static string Provision_Commission {
            get {
                return ResourceManager.GetString("Provision_Commission", resourceCulture);
            }
        }
        
        internal static string Provision_DeviceId {
            get {
                return ResourceManager.GetString("Provision_DeviceId", resourceCulture);
            }
        }
        
        internal static string Provision_DeviceType {
            get {
                return ResourceManager.GetString("Provision_DeviceType", resourceCulture);
            }
        }
        
        internal static string Provision_Firmware_SKU {
            get {
                return ResourceManager.GetString("Provision_Firmware_SKU", resourceCulture);
            }
        }
        
        internal static string Provision_Firmware_Version {
            get {
                return ResourceManager.GetString("Provision_Firmware_Version", resourceCulture);
            }
        }
        
        internal static string Provision_GPSEnabled {
            get {
                return ResourceManager.GetString("Provision_GPSEnabled", resourceCulture);
            }
        }
        
        internal static string Provision_GPSUpdateRate {
            get {
                return ResourceManager.GetString("Provision_GPSUpdateRate", resourceCulture);
            }
        }
        
        internal static string Provision_Hardware_Version {
            get {
                return ResourceManager.GetString("Provision_Hardware_Version", resourceCulture);
            }
        }
        
        internal static string Provision_PingUpdateRate {
            get {
                return ResourceManager.GetString("Provision_PingUpdateRate", resourceCulture);
            }
        }
        
        internal static string Provision_Reboot {
            get {
                return ResourceManager.GetString("Provision_Reboot", resourceCulture);
            }
        }
        
        internal static string Provision_ResetProfile {
            get {
                return ResourceManager.GetString("Provision_ResetProfile", resourceCulture);
            }
        }
        
        internal static string Provision_Server_Anonymous {
            get {
                return ResourceManager.GetString("Provision_Server_Anonymous", resourceCulture);
            }
        }
        
        internal static string Provision_Server_Host {
            get {
                return ResourceManager.GetString("Provision_Server_Host", resourceCulture);
            }
        }
        
        internal static string Provision_Server_Password {
            get {
                return ResourceManager.GetString("Provision_Server_Password", resourceCulture);
            }
        }
        
        internal static string Provision_Server_UserId {
            get {
                return ResourceManager.GetString("Provision_Server_UserId", resourceCulture);
            }
        }
        
        internal static string Provision_SrvrUpdateRate {
            get {
                return ResourceManager.GetString("Provision_SrvrUpdateRate", resourceCulture);
            }
        }
        
        internal static string Provision_VerboseLogging {
            get {
                return ResourceManager.GetString("Provision_VerboseLogging", resourceCulture);
            }
        }
        
        internal static string Provision_WiFiEnabled {
            get {
                return ResourceManager.GetString("Provision_WiFiEnabled", resourceCulture);
            }
        }
        
        internal static string Provision_WiFi_Pwd {
            get {
                return ResourceManager.GetString("Provision_WiFi_Pwd", resourceCulture);
            }
        }
        
        internal static string Provision_WiFi_SSID {
            get {
                return ResourceManager.GetString("Provision_WiFi_SSID", resourceCulture);
            }
        }
        
        internal static string Provision_WriteProfile {
            get {
                return ResourceManager.GetString("Provision_WriteProfile", resourceCulture);
            }
        }
    }
}
