//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BugLogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BugLogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BugLog.BugLogResources", typeof(BugLogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Logistics Bug/Log.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Common_Exit {
            get {
                return ResourceManager.GetString("Common_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string Common_GetStarted {
            get {
                return ResourceManager.GetString("Common_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -select command-.
        /// </summary>
        internal static string Common_SelectCommand {
            get {
                return ResourceManager.GetString("Common_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ComponentView_Configuration {
            get {
                return ResourceManager.GetString("ComponentView_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Registered BugLog Monitoring Devices.
        /// </summary>
        internal static string MainView_NoRegisteredDevices {
            get {
                return ResourceManager.GetString("MainView_NoRegisteredDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Your Device.
        /// </summary>
        internal static string PairDevice_Title {
            get {
                return ResourceManager.GetString("PairDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Address.
        /// </summary>
        internal static string Provision_BT_Address {
            get {
                return ResourceManager.GetString("Provision_BT_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular Enabled.
        /// </summary>
        internal static string Provision_CellEnabled {
            get {
                return ResourceManager.GetString("Provision_CellEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        internal static string Provision_Commission {
            get {
                return ResourceManager.GetString("Provision_Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        internal static string Provision_DeviceId {
            get {
                return ResourceManager.GetString("Provision_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        internal static string Provision_DeviceType {
            get {
                return ResourceManager.GetString("Provision_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware SKU.
        /// </summary>
        internal static string Provision_Firmware_SKU {
            get {
                return ResourceManager.GetString("Provision_Firmware_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        internal static string Provision_Firmware_Version {
            get {
                return ResourceManager.GetString("Provision_Firmware_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Enabled.
        /// </summary>
        internal static string Provision_GPSEnabled {
            get {
                return ResourceManager.GetString("Provision_GPSEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Update Rate (seconds).
        /// </summary>
        internal static string Provision_GPSUpdateRate {
            get {
                return ResourceManager.GetString("Provision_GPSUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Version.
        /// </summary>
        internal static string Provision_Hardware_Version {
            get {
                return ResourceManager.GetString("Provision_Hardware_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Update Rate (seconds).
        /// </summary>
        internal static string Provision_PingUpdateRate {
            get {
                return ResourceManager.GetString("Provision_PingUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string Provision_Reboot {
            get {
                return ResourceManager.GetString("Provision_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Profile.
        /// </summary>
        internal static string Provision_ResetProfile {
            get {
                return ResourceManager.GetString("Provision_ResetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Anonymous Login.
        /// </summary>
        internal static string Provision_Server_Anonymous {
            get {
                return ResourceManager.GetString("Provision_Server_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Host Name.
        /// </summary>
        internal static string Provision_Server_Host {
            get {
                return ResourceManager.GetString("Provision_Server_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Password.
        /// </summary>
        internal static string Provision_Server_Password {
            get {
                return ResourceManager.GetString("Provision_Server_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server User Id.
        /// </summary>
        internal static string Provision_Server_UserId {
            get {
                return ResourceManager.GetString("Provision_Server_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Update Rate (seconds).
        /// </summary>
        internal static string Provision_SrvrUpdateRate {
            get {
                return ResourceManager.GetString("Provision_SrvrUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose Logging.
        /// </summary>
        internal static string Provision_VerboseLogging {
            get {
                return ResourceManager.GetString("Provision_VerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Password.
        /// </summary>
        internal static string Provision_WiFi_Pwd {
            get {
                return ResourceManager.GetString("Provision_WiFi_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi SSID.
        /// </summary>
        internal static string Provision_WiFi_SSID {
            get {
                return ResourceManager.GetString("Provision_WiFi_SSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Enabled.
        /// </summary>
        internal static string Provision_WiFiEnabled {
            get {
                return ResourceManager.GetString("Provision_WiFiEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Profile.
        /// </summary>
        internal static string Provision_WriteProfile {
            get {
                return ResourceManager.GetString("Provision_WriteProfile", resourceCulture);
            }
        }
    }
}
